[package]
name = "usb-probester"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[lib]
name = "usb_probester_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
hid-parser = { path = "../crates/hid-parser" }
tauri-specta = { version = "=2.0.0-rc.25", features = ["derive", "typescript"] }
serde = { workspace = true }
serde_json = { workspace = true }
specta = { workspace = true }
specta-typescript = { workspace = true }
usb-types = { path = "../crates/usb-types" }

[target.'cfg(target_os = "macos")'.dependencies]
usb-collector-macos = { path = "../crates/usb-collector-macos" }

[target.'cfg(target_os = "linux")'.dependencies]
usb-collector-linux = { path = "../crates/usb-collector-linux" }
