[package]
name = "usb-cli"
version.workspace = true
edition = "2021"

[[bin]]
name = "usb-probester-cli"
path = "src/main.rs"

[dependencies]
usb-types = { path = "../usb-types" }
usb-formatter = { path = "../usb-formatter" }
serde_json = { workspace = true }
clap = { version = "4", features = ["derive"] }
usb-ids = "1.2025.2"

[target.'cfg(target_os = "macos")'.dependencies]
usb-collector-macos = { path = "../usb-collector-macos" }

[target.'cfg(target_os = "linux")'.dependencies]
usb-collector-linux = { path = "../usb-collector-linux" }

[target.'cfg(target_os = "windows")'.dependencies]
usb-collector-windows = { path = "../usb-collector-windows" }
